In [1]:
import pandas as pd

In [64]:
def getVotingResult(df):

    optionList = ['Adaptation WITHIN Ordinary', 'Chances WITHIN Reach/Doorstep', 'Data WITHIN Users', 
                 'Decentralization WITHIN Resilience', 'Flexibility WITHIN Resilience', 'Individual WITHIN Crowd',
                 'Normality WITHIN Resilience', 'Resilience WITHIN Order', 'Space WITHIN Epidemic', 'Parking WITHIN Reach']

    # list all voters and options
    votees = list(df)
    del votees[0]
    votees

    # list all options
    options = []
    for i in range(10):
        options.append(str(i+1))

    #list all voters
    voters = [ 'A','B','C','D','E','F','G','H','I','J','K','L']

    df = df.drop(columns = ['name'])
    df['total'] = df.apply(lambda x: x.sum(), axis=1)  # count the total ballots of every voter

    for i in range(len(df)):
        df.iloc[i] = df.iloc[i]/df['total'][i]*100  # normalize the total ballots of every voter to 100

    # df1 for options, df2 for voters    
    df1 = df.iloc[:, 0:10]
    df2 = df.iloc[:,10:-1]

    df1['counts'] = df1.apply(lambda x: x.sum(), axis=1)  # calculate how many ballots every voter give to options
    df2.loc['ballots'] = df2.apply(lambda x: x.sum()) # calculate how many ballots every voter get from voters

    # calculate how many ballots every voter give to options after being weighted by the ballots from voters
    for i in range(len(df)):
        df1['realCounts'] = df1['counts']+df2[voters[i]]['ballots']

    # calculate how many ballots every option per voter gets after being weighted by the ballots from voters    
    for i in range(len(df1)):
        for option in options:
            df1[option][i] = df1[option][i]*df1['realCounts'][i]/df1['counts'][i]

    # calculate final total ballots of every option 
    result = {}
    for option in options:
        result[option] = sum(df1[option])

    results = {}
    for i in range(len(options)):
        results[optionList[i]] = sum(df1[options[i]])

    # get the best 2 options
    btos = sorted(list(result.values()), reverse = True)
    first = list(result.values()).index(btos[0])
    second = list(result.values()).index(btos[1])
    print('The first option is: '+ optionList[first])
    print('The second option is: '+ optionList[second])
    print('===================================================')
    print('The complete results:')
    return results

In [62]:
df = pd.read_csv('./realData.csv')
df

,name,1,2,3,4,5,6,7,8,9,...,C,D,E,F,G,H,I,J,K,L
0,A,85,0,0,0,55,70,0,0,0,...,99,29,99,49,49,49,79,29,79,49
1,B,0,0,0,30,100,0,90,0,0,...,0,0,0,0,0,0,0,0,0,0
2,C,100,100,100,0,100,100,0,100,100,...,0,0,100,100,0,100,0,0,100,0
3,D,80,0,70,90,90,85,0,0,0,...,100,0,100,100,0,100,0,0,100,0
4,E,83,73,86,93,71,76,93,74,57,...,0,0,0,0,0,0,0,0,0,0
5,F,0,0,0,0,0,0,0,0,50,...,0,0,30,0,90,95,0,0,30,90
6,G,80,0,0,20,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,30
7,H,50,0,0,20,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,I,90,70,0,70,65,75,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,J,0,0,0,20,0,0,40,0,40,...,0,0,0,0,0,0,0,0,0,0
10,K,20,0,0,10,0,0,40,0,0,...,0,0,0,15,0,15,0,0,0,0
11,L,0,0,35,35,0,0,0,0,0,...,10,0,10,0,10,0,0,0,0,0

In [65]:
getVotingResult(df)

The first option is: Adaptation WITHIN Ordinary
The second option is: Decentralization WITHIN Resilience
===================================================
The complete results:

{'Adaptation WITHIN Ordinary': 345.518955775352,
 'Chances WITHIN Reach/Doorstep': 54.716668511312704,
 'Data WITHIN Users': 103.75616844639751,
 'Decentralization WITHIN Resilience': 252.64449799540577,
 'Flexibility WITHIN Resilience': 137.40192489476252,
 'Individual WITHIN Crowd': 96.23836788774256,
 'Normality WITHIN Resilience': 188.06533235374567,
 'Resilience WITHIN Order': 26.95944965213728,
 'Space WITHIN Epidemic': 117.46524582233852,
 'Parking WITHIN Reach': 119.69840528677595}

In [51]:
df = pd.read_csv('./votingResultsDemo.csv')
df

,name,1,2,3,4,5,6,7,8,9,...,C,D,E,F,G,H,I,J,K,L
0,A,75,44,6,66,88,99,0,5,88,...,55,6,88,8,9,34,88,99,4,77
1,B,55,6,88,8,9,34,88,99,0,...,0,5,88,3,6,66,7,9,8,1
2,C,88,8,9,99,0,5,88,4,6,...,88,6,36,66,88,12,89,66,77,88
3,D,3,55,23,44,44,6,66,88,99,...,88,12,89,8,9,44,6,2,1,88
4,E,62,88,99,0,6,88,8,9,34,...,9,44,6,99,0,6,88,5,6,36
5,F,3,5,55,22,8,9,99,0,5,...,0,6,88,6,7,8,9,99,6,89
6,G,62,88,99,6,99,0,33,66,4,...,55,8,9,88,3,45,45,12,89,6
7,H,4,75,44,99,0,5,88,3,5,...,3,45,45,99,0,66,88,44,6,88
8,I,3,55,55,34,88,99,99,0,99,...,0,66,88,99,0,5,3,6,88,9
9,J,6,99,0,5,88,4,0,5,4,...,88,8,9,34,88,99,4,8,9,45
10,K,99,0,5,44,5,34,88,99,5,...,9,99,0,5,88,4,5,45,45,88
11,L,34,88,99,33,12,5,88,4,8,...,9,99,8,9,99,7,6,66,88,9

In [3]:
votees = list(df)
del votees[0]
votees

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L']

In [4]:
options = []
for i in range(10):
    options.append(str(i+1))
    
options

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [5]:
voters = [ 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L']
voters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']

In [31]:
X = len(voters)
Y = len(options)
(X,Y)

(12, 10)

In [19]:
df = df.drop(columns = ['name'])
df

,1,2,3,4,5,6,7,8,9,10,...,C,D,E,F,G,H,I,J,K,L
0,75,44,6,66,88,99,0,5,88,3,...,55,6,88,8,9,34,88,99,4,77
1,55,6,88,8,9,34,88,99,0,62,...,0,5,88,3,6,66,7,9,8,1
2,88,8,9,99,0,5,88,4,6,99,...,88,6,36,66,88,12,89,66,77,88
3,3,55,23,44,44,6,66,88,99,0,...,88,12,89,8,9,44,6,2,1,88
4,62,88,99,0,6,88,8,9,34,88,...,9,44,6,99,0,6,88,5,6,36
5,3,5,55,22,8,9,99,0,5,88,...,0,6,88,6,7,8,9,99,6,89
6,62,88,99,6,99,0,33,66,4,55,...,55,8,9,88,3,45,45,12,89,6
7,4,75,44,99,0,5,88,3,5,88,...,3,45,45,99,0,66,88,44,6,88
8,3,55,55,34,88,99,99,0,99,45,...,0,66,88,99,0,5,3,6,88,9
9,6,99,0,5,88,4,0,5,4,7,...,88,8,9,34,88,99,4,8,9,45
10,99,0,5,44,5,34,88,99,5,7,...,9,99,0,5,88,4,5,45,45,88
11,34,88,99,33,12,5,88,4,8,7,...,9,99,8,9,99,7,6,66,88,9

In [20]:
df['total'] = df.apply(lambda x: x.sum(), axis=1)
df

,1,2,3,4,5,6,7,8,9,10,...,D,E,F,G,H,I,J,K,L,total
0,75,44,6,66,88,99,0,5,88,3,...,6,88,8,9,34,88,99,4,77,1041
1,55,6,88,8,9,34,88,99,0,62,...,5,88,3,6,66,7,9,8,1,829
2,88,8,9,99,0,5,88,4,6,99,...,6,36,66,88,12,89,66,77,88,1027
3,3,55,23,44,44,6,66,88,99,0,...,12,89,8,9,44,6,2,1,88,846
4,62,88,99,0,6,88,8,9,34,88,...,44,6,99,0,6,88,5,6,36,888
5,3,5,55,22,8,9,99,0,5,88,...,6,88,6,7,8,9,99,6,89,715
6,62,88,99,6,99,0,33,66,4,55,...,8,9,88,3,45,45,12,89,6,1004
7,4,75,44,99,0,5,88,3,5,88,...,45,45,99,0,66,88,44,6,88,986
8,3,55,55,34,88,99,99,0,99,45,...,66,88,99,0,5,3,6,88,9,1046
9,6,99,0,5,88,4,0,5,4,7,...,8,9,34,88,99,4,8,9,45,671
10,99,0,5,44,5,34,88,99,5,7,...,99,0,5,88,4,5,45,45,88,870
11,34,88,99,33,12,5,88,4,8,7,...,99,8,9,99,7,6,66,88,9,794

In [21]:
for i in range(len(df)):
    df.iloc[i] = df.iloc[i]/df['total'][i]*100
    
df

,1,2,3,4,5,6,7,8,9,10,...,D,E,F,G,H,I,J,K,L,total
0,7.204611,4.226705,0.576369,6.340058,8.453410,9.510086,0.000000,0.480307,8.453410,0.288184,...,0.576369,8.453410,0.768492,0.864553,3.266090,8.453410,9.510086,0.384246,7.396734,100
1,6.634499,0.723764,10.615199,0.965018,1.085645,4.101327,10.615199,11.942099,0.000000,7.478890,...,0.603136,10.615199,0.361882,0.723764,7.961399,0.844391,1.085645,0.965018,0.120627,100
2,8.568647,0.778968,0.876339,9.639727,0.000000,0.486855,8.568647,0.389484,0.584226,9.639727,...,0.584226,3.505355,6.426485,8.568647,1.168452,8.666018,6.426485,7.497566,8.568647,100
3,0.354610,6.501182,2.718676,5.200946,5.200946,0.709220,7.801418,10.401891,11.702128,0.000000,...,1.418440,10.520095,0.945626,1.063830,5.200946,0.709220,0.236407,0.118203,10.401891,100
4,6.981982,9.909910,11.148649,0.000000,0.675676,9.909910,0.900901,1.013514,3.828829,9.909910,...,4.954955,0.675676,11.148649,0.000000,0.675676,9.909910,0.563063,0.675676,4.054054,100
5,0.419580,0.699301,7.692308,3.076923,1.118881,1.258741,13.846154,0.000000,0.699301,12.307692,...,0.839161,12.307692,0.839161,0.979021,1.118881,1.258741,13.846154,0.839161,12.447552,100
6,6.175299,8.764940,9.860558,0.597610,9.860558,0.000000,3.286853,6.573705,0.398406,5.478088,...,0.796813,0.896414,8.764940,0.298805,4.482072,4.482072,1.195219,8.864542,0.597610,100
7,0.405680,7.606491,4.462475,10.040568,0.000000,0.507099,8.924949,0.304260,0.507099,8.924949,...,4.563895,4.563895,10.040568,0.000000,6.693712,8.924949,4.462475,0.608519,8.924949,100
8,0.286807,5.258126,5.258126,3.250478,8.413002,9.464627,9.464627,0.000000,9.464627,4.302103,...,6.309751,8.413002,9.464627,0.000000,0.478011,0.286807,0.573614,8.413002,0.860421,100
9,0.894188,14.754098,0.000000,0.745156,13.114754,0.596125,0.000000,0.745156,0.596125,1.043219,...,1.192250,1.341282,5.067064,13.114754,14.754098,0.596125,1.192250,1.341282,6.706408,100
10,11.379310,0.000000,0.574713,5.057471,0.574713,3.908046,10.114943,11.379310,0.574713,0.804598,...,11.379310,0.000000,0.574713,10.114943,0.459770,0.574713,5.172414,5.172414,10.114943,100
11,4.282116,11.083123,12.468514,4.156171,1.511335,0.629723,11.083123,0.503778,1.007557,0.881612,...,12.468514,1.007557,1.133501,12.468514,0.881612,0.755668,8.312343,11.083123,1.133501,100

In [22]:
df1 = df.iloc[:, 0:10]
df2 = df.iloc[:,10:-1]

In [23]:
df1

,1,2,3,4,5,6,7,8,9,10
0,7.204611,4.226705,0.576369,6.340058,8.453410,9.510086,0.000000,0.480307,8.453410,0.288184
1,6.634499,0.723764,10.615199,0.965018,1.085645,4.101327,10.615199,11.942099,0.000000,7.478890
2,8.568647,0.778968,0.876339,9.639727,0.000000,0.486855,8.568647,0.389484,0.584226,9.639727
3,0.354610,6.501182,2.718676,5.200946,5.200946,0.709220,7.801418,10.401891,11.702128,0.000000
4,6.981982,9.909910,11.148649,0.000000,0.675676,9.909910,0.900901,1.013514,3.828829,9.909910
5,0.419580,0.699301,7.692308,3.076923,1.118881,1.258741,13.846154,0.000000,0.699301,12.307692
6,6.175299,8.764940,9.860558,0.597610,9.860558,0.000000,3.286853,6.573705,0.398406,5.478088
7,0.405680,7.606491,4.462475,10.040568,0.000000,0.507099,8.924949,0.304260,0.507099,8.924949
8,0.286807,5.258126,5.258126,3.250478,8.413002,9.464627,9.464627,0.000000,9.464627,4.302103
9,0.894188,14.754098,0.000000,0.745156,13.114754,0.596125,0.000000,0.745156,0.596125,1.043219
10,11.379310,0.000000,0.574713,5.057471,0.574713,3.908046,10.114943,11.379310,0.574713,0.804598
11,4.282116,11.083123,12.468514,4.156171,1.511335,0.629723,11.083123,0.503778,1.007557,0.881612

In [24]:
df2

,A,B,C,D,E,F,G,H,I,J,K,L
0,5.283381,4.226705,5.283381,0.576369,8.453410,0.768492,0.864553,3.266090,8.453410,9.510086,0.384246,7.396734
1,10.615199,11.942099,0.000000,0.603136,10.615199,0.361882,0.723764,7.961399,0.844391,1.085645,0.965018,0.120627
2,0.000000,0.486855,8.568647,0.584226,3.505355,6.426485,8.568647,1.168452,8.666018,6.426485,7.497566,8.568647
3,0.591017,7.801418,10.401891,1.418440,10.520095,0.945626,1.063830,5.200946,0.709220,0.236407,0.118203,10.401891
4,11.148649,0.900901,1.013514,4.954955,0.675676,11.148649,0.000000,0.675676,9.909910,0.563063,0.675676,4.054054
5,0.559441,13.846154,0.000000,0.839161,12.307692,0.839161,0.979021,1.118881,1.258741,13.846154,0.839161,12.447552
6,5.478088,7.669323,5.478088,0.796813,0.896414,8.764940,0.298805,4.482072,4.482072,1.195219,8.864542,0.597610
7,0.304260,8.924949,0.304260,4.563895,4.563895,10.040568,0.000000,6.693712,8.924949,4.462475,0.608519,8.924949
8,0.573614,9.464627,0.000000,6.309751,8.413002,9.464627,0.000000,0.478011,0.286807,0.573614,8.413002,0.860421
9,8.196721,0.894188,13.114754,1.192250,1.341282,5.067064,13.114754,14.754098,0.596125,1.192250,1.341282,6.706408
10,10.114943,0.919540,1.034483,11.379310,0.000000,0.574713,10.114943,0.459770,0.574713,5.172414,5.172414,10.114943
11,1.007557,1.007557,1.133501,12.468514,1.007557,1.133501,12.468514,0.881612,0.755668,8.312343,11.083123,1.133501

In [29]:
df1['counts'] = df1.apply(lambda x: x.sum(), axis=1)
df1

,1,2,3,4,5,6,7,8,9,10,counts
0,7.204611,4.226705,0.576369,6.340058,8.453410,9.510086,0.000000,0.480307,8.453410,0.288184,45.533141
1,6.634499,0.723764,10.615199,0.965018,1.085645,4.101327,10.615199,11.942099,0.000000,7.478890,54.161641
2,8.568647,0.778968,0.876339,9.639727,0.000000,0.486855,8.568647,0.389484,0.584226,9.639727,39.532619
3,0.354610,6.501182,2.718676,5.200946,5.200946,0.709220,7.801418,10.401891,11.702128,0.000000,50.591017
4,6.981982,9.909910,11.148649,0.000000,0.675676,9.909910,0.900901,1.013514,3.828829,9.909910,54.279279
5,0.419580,0.699301,7.692308,3.076923,1.118881,1.258741,13.846154,0.000000,0.699301,12.307692,41.118881
6,6.175299,8.764940,9.860558,0.597610,9.860558,0.000000,3.286853,6.573705,0.398406,5.478088,50.996016
7,0.405680,7.606491,4.462475,10.040568,0.000000,0.507099,8.924949,0.304260,0.507099,8.924949,41.683570
8,0.286807,5.258126,5.258126,3.250478,8.413002,9.464627,9.464627,0.000000,9.464627,4.302103,55.162524
9,0.894188,14.754098,0.000000,0.745156,13.114754,0.596125,0.000000,0.745156,0.596125,1.043219,32.488823
10,11.379310,0.000000,0.574713,5.057471,0.574713,3.908046,10.114943,11.379310,0.574713,0.804598,44.367816
11,4.282116,11.083123,12.468514,4.156171,1.511335,0.629723,11.083123,0.503778,1.007557,0.881612,47.607053

In [30]:
df2.loc['ballots'] = df2.apply(lambda x: x.sum())
df2

,A,B,C,D,E,F,G,H,I,J,K,L
0,5.283381,4.226705,5.283381,0.576369,8.453410,0.768492,0.864553,3.266090,8.453410,9.510086,0.384246,7.396734
1,10.615199,11.942099,0.000000,0.603136,10.615199,0.361882,0.723764,7.961399,0.844391,1.085645,0.965018,0.120627
2,0.000000,0.486855,8.568647,0.584226,3.505355,6.426485,8.568647,1.168452,8.666018,6.426485,7.497566,8.568647
3,0.591017,7.801418,10.401891,1.418440,10.520095,0.945626,1.063830,5.200946,0.709220,0.236407,0.118203,10.401891
4,11.148649,0.900901,1.013514,4.954955,0.675676,11.148649,0.000000,0.675676,9.909910,0.563063,0.675676,4.054054
5,0.559441,13.846154,0.000000,0.839161,12.307692,0.839161,0.979021,1.118881,1.258741,13.846154,0.839161,12.447552
6,5.478088,7.669323,5.478088,0.796813,0.896414,8.764940,0.298805,4.482072,4.482072,1.195219,8.864542,0.597610
7,0.304260,8.924949,0.304260,4.563895,4.563895,10.040568,0.000000,6.693712,8.924949,4.462475,0.608519,8.924949
8,0.573614,9.464627,0.000000,6.309751,8.413002,9.464627,0.000000,0.478011,0.286807,0.573614,8.413002,0.860421
9,8.196721,0.894188,13.114754,1.192250,1.341282,5.067064,13.114754,14.754098,0.596125,1.192250,1.341282,6.706408
10,10.114943,0.919540,1.034483,11.379310,0.000000,0.574713,10.114943,0.459770,0.574713,5.172414,5.172414,10.114943
11,1.007557,1.007557,1.133501,12.468514,1.007557,1.133501,12.468514,0.881612,0.755668,8.312343,11.083123,1.133501
ballots,53.872868,68.084316,46.332518,45.686820,62.299576,55.535708,48.196829,47.140720,45.462023,52.576155,45.962751,71.327337

In [33]:
for i in range(len(df)):
    df1['realCounts'] = df1['counts']+df2[voters[i]]['ballots']
    
df1

,1,2,3,4,5,6,7,8,9,10,counts,realCounts
0,7.204611,4.226705,0.576369,6.340058,8.453410,9.510086,0.000000,0.480307,8.453410,0.288184,45.533141,116.860478
1,6.634499,0.723764,10.615199,0.965018,1.085645,4.101327,10.615199,11.942099,0.000000,7.478890,54.161641,125.488978
2,8.568647,0.778968,0.876339,9.639727,0.000000,0.486855,8.568647,0.389484,0.584226,9.639727,39.532619,110.859956
3,0.354610,6.501182,2.718676,5.200946,5.200946,0.709220,7.801418,10.401891,11.702128,0.000000,50.591017,121.918354
4,6.981982,9.909910,11.148649,0.000000,0.675676,9.909910,0.900901,1.013514,3.828829,9.909910,54.279279,125.606616
5,0.419580,0.699301,7.692308,3.076923,1.118881,1.258741,13.846154,0.000000,0.699301,12.307692,41.118881,112.446218
6,6.175299,8.764940,9.860558,0.597610,9.860558,0.000000,3.286853,6.573705,0.398406,5.478088,50.996016,122.323353
7,0.405680,7.606491,4.462475,10.040568,0.000000,0.507099,8.924949,0.304260,0.507099,8.924949,41.683570,113.010907
8,0.286807,5.258126,5.258126,3.250478,8.413002,9.464627,9.464627,0.000000,9.464627,4.302103,55.162524,126.489861
9,0.894188,14.754098,0.000000,0.745156,13.114754,0.596125,0.000000,0.745156,0.596125,1.043219,32.488823,103.816160
10,11.379310,0.000000,0.574713,5.057471,0.574713,3.908046,10.114943,11.379310,0.574713,0.804598,44.367816,115.695153
11,4.282116,11.083123,12.468514,4.156171,1.511335,0.629723,11.083123,0.503778,1.007557,0.881612,47.607053,118.934390

In [36]:
for i in range(len(df1)):
    for option in options:
        df1[option][i] = df1[option][i]*df1['realCounts'][i]/df1['counts'][i]
df1

,1,2,3,4,5,6,7,8,9,10,counts,realCounts
0,18.490582,10.847808,1.479247,16.271712,21.695616,24.407568,0.000000,1.232705,21.695616,0.739623,45.533141,116.860478
1,15.371701,1.676913,24.594722,2.235884,2.515369,9.502506,24.594722,27.669062,0.000000,17.328099,54.161641,125.488978
2,24.028759,2.184433,2.457487,27.032354,0.000000,1.365270,24.028759,1.092216,1.638324,27.032354,39.532619,110.859956
3,0.854568,15.667078,6.551687,12.533663,12.533663,1.709136,18.800494,25.067325,28.200741,0.000000,50.591017,121.918354
4,16.156868,22.932328,25.798869,0.000000,1.563568,22.932328,2.084757,2.345352,8.860218,22.932328,54.279279,125.606616
5,1.147410,1.912351,21.035857,8.414343,3.059761,3.442231,37.864543,0.000000,1.912351,33.657371,41.118881,112.446218
6,14.812594,21.024326,23.652367,1.433477,23.652367,0.000000,7.884122,15.768245,0.955651,13.140204,50.996016,122.323353
7,1.099863,20.622428,12.098491,27.221605,0.000000,1.374829,24.196983,0.824897,1.374829,24.196983,41.683570,113.010907
8,0.657660,12.057092,12.057092,7.453475,19.291348,21.702766,21.702766,0.000000,21.702766,9.864894,55.162524,126.489861
9,2.857325,47.145871,0.000000,2.381105,41.907441,1.904884,0.000000,2.381105,1.904884,3.333546,32.488823,103.816160
10,29.673109,0.000000,1.498642,13.188049,1.498642,10.190765,26.376097,29.673109,1.498642,2.098099,44.367816,115.695153
11,10.697802,27.688429,31.149483,10.383161,3.775695,1.573206,27.688429,1.258565,2.517130,2.202489,47.607053,118.934390

In [38]:
result = {}
for option in options:
    result[option] = sum(df1[option])
    
result

{'1': 135.84824101244737,
 '2': 183.75905791091566,
 '3': 162.37394448197813,
 '4': 128.5488269007269,
 '5': 131.49346937569965,
 '6': 100.10548969915652,
 '7': 215.22167234122878,
 '8': 107.3125811339848,
 '9': 92.26115147944225,
 '10': 156.525990351997}

In [45]:
btos = sorted(list(result.values()), reverse = True)
btos

[215.22167234122878,
 183.75905791091566,
 162.37394448197813,
 156.525990351997,
 135.84824101244737,
 131.49346937569965,
 128.5488269007269,
 107.3125811339848,
 100.10548969915652,
 92.26115147944225]

In [48]:
first = list(result.values()).index(btos[0])
second = list(result.values()).index(btos[1])

In [49]:
optionList = ['Adaptation WITHIN Ordinary', 'Chances WITHIN Reach/Doorstep', 'Data WITHIN Users', 
             'Decentralization WITHIN Resilience', 'Flexibility WITHIN Resilience', 'Individual WITHIN Crowd',
             'Normality WITHIN Resilience', 'Resilience WITHIN Order', 'Space WITHIN Epidemic', 'Transit WITHIN ...']